version: 2
updates:
  # 1. Check for Docker Image updates
  - package-ecosystem: "docker-compose"
    directory: "/media-stack" # Folder where your media docker-compose lives
    schedule:
      interval: "weekly" # Check every week (prevents notification spam)
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  # 2. Check for Monitoring updates
  - package-ecosystem: "docker-compose"
    directory: "/monitoring" # Folder where your prometheus docker-compose lives
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

