global:
  resolve_timeout: 5m

route:
  receiver: "gotify"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: "gotify"
    webhook_configs:
      - url: "http://alertmanager_gotify_bridge:8080/gotify_webhook"
        send_resolved: true
